#+TITLE: AAG: Questões, Aula #1
#+LANGUAGE: br
#+options: author:nil  email:nil
#+LATEX_HEADER: \author{Gustavo de Paula\\ \texttt{\href{mailto:gustavodepaula@disroot.org}{gustavodepaula@disroot.org}}}
#+LATEX_HEADER: \input{structure.tex}
#+LATEX_HEADER: \usepackage[portuguese]{babel}

* O que é produtividade e como se obtém?
Produtividade é a relação entre o quanto e a qualidade do que foi produzido e o
valor e quantidade dos recursos aplicados na produção.
Para se obter produtividade é necessário aumentar a quantidade e a qualidade do
que é produzido por unidade de recurso consumida.
Para se obter uma maior produtividade, pode se melhorar a performance, cortar
custos, e aumentar a eficiência e eficácia da produção.

* O que é fordismo e economia de escala?
** Fordismo
Fordismo é um modo de produção que faz uso do sistema de linha de produção para
atingir três objetivos principais: intensificação (dinamismo do tempo de
produção), economia (manutenção da produção equilibrada com seus estoques),
produtividade (extrair o máximo da mão de obra de cada trabalhador).

** Economia de escala
Podemos dizer que há economia de escala quando a expansão da capacidade de
produção provoca um aumento no total na quantidade produzida sem aumento
proporcional ou linear nos custos de produção.

* Como se obtém produtividade no desenvolvimento de software?
Não há consenso sobre como se obtém produtividade no desenvolvimento de
software. Porém, ao se conversar com alguns gerentes de produto, alguns pontos
foram levantados:
- Metas: o time de desenvolvimento deve estar claro do que é esperado
- Autonomia: o time deve ser livre para trabalhar em cima do prazo e propostas
  acordadas
- Comunicação: é necessário haver uma clara comunicação entre todas as partes
  envolvidas na entrega do produto.

* Como é uma fábrica de software?
Uma fábrica de software é uma empresa que não tem um produto próprio e presta
consultoria e desenvolvimento, este último principalmente para empresas pequenas
que não possuem um time de desenvolvimento.

* Metodologia de desenvolvimento de software. Quais são e como são?
Há varias metodologias de desenvolvimento de software, os mais relevantes hoje
são divididos nas seguintes categorias:
** Iterativas (ágeis)
As metodologias de desenvolvimento ágil são aquelas que fazem usos de iterações
ou /sprints/. Cada iteração dura de uma a quatro semanas. Em uma sprint, o time
passa por todas as fases de desenvolvimento (análises, design, programação e
teste) e no final, o resultado é apresentado à stakeholders e clientes que podem
dar feedback antes do sistema como todo estar pronto.

** Cascata (waterfall)
As metodologias de desenvolvimento em cascata são aquelas onde o desenvolvimento
é feito linearmente separados em várias fases, com pouca flexibilidade e
iteração. As fases de um desenvolvimento em cascata costumam ser divididas nas
seguintes fases:
- Documentação dos requerimentos do produto
- Análise, onde modelos e regras de negócios são resultados
- Design, onde a arquitetura do software é feita
- Programação, onde o desenvolvimento é feito
- Teste, onde há o descobrimento e conserto de bugs
- Operação, onde há a instalação, suporte e manutenção do sistema

